### ISSUE TITLE
The parameter hostName of ElasticsearchRestIndex needs the prefix "http://"

### ISSUE THREAD

**Issue by rzbhatti** [IBMStreams/streamsx.elasticsearch#7]
If parameter hostName does not have "http://"  prefixed the operator ElasticsearchRestIndex crashed in runtime
I have fixed it as following :

	public void setHostName(String hostName) {
		if ( hostName.matches("^http://.*") ) {
			this.hostName = hostName;
		} else {
			this.hostName = "http://" + hostName;
		}
	}

**Comment by nelsonong** [comment]
Thanks for catching this. I have added it here: https://github.com/IBMStreams/streamsx.elasticsearch/commit/ad2c7d6e893a2b249464b38e65764eb9f82661ac.
