### ISSUE TITLE
ElasticsearchRestIndex : An rstring  attribute with empty runtime value "" caused error

### ISSUE THREAD

**Issue by rzbhatti** [IBMStreams/streamsx.elasticsearch#8]
If a rstring attribute comes empty like "", it throws error and crashes.  
I have fixed it as following :

    	for(String attributeName : attributeNames) {
    		if ( schema.getAttribute(attributeName).getType().getMetaType() == Type.MetaType.RSTRING ) {
    			jsonFields.put(attributeName, tuple.getObject(attributeName).toString());
    		} else {
    			jsonFields.put(attributeName, tuple.getObject(attributeName));
    		}
    	}

**Comment by nelsonong** [comment]
Thanks for catching this. I have added it here: https://github.com/IBMStreams/streamsx.elasticsearch/commit/b44268a7eba36ebca265dc13bc690799da6c578b.
